language: node_js
node_js:
  - 12
install:
  - npm ci
script:
  - npm run build-example
  - npm run build
deploy:
  - provider: script
    skip_cleanup: true
    script: bash deploy.sh
    on:
      tags: true
env:
  global:
    - secure: xjo8XimbAEUz1lo3lAeWJaL6VxWu2bnovBwI7pXw3YCniVK0CeuNm7hmO4Ts2WNGzj72A5GFMaITtlAwdDrXvQSRY9xZZMW/4CGWDBmZX/7bXNNZMpmpA6/XWkU8I5PasX0sASgmaUGuFrG++m1LKjUE/5SzWnyheviM6N4PpsdzuaFhRoY8tUzwX7TDjX7m2ZhQuo+1WOXD9seXu+9RVnl0Z17b2euWUen/fEHCjUXkTvSbelpNXmirYRteZeEIE5Ax8KxsHv7BWQVcCbY3/yZu4Vl/0Poqf56RnwEAPGUcJh1lZr2NMflc+lJmTN7t2sbkgrJk5s3IWyClHBFsbpVmq6jE0Z5uxz36ucwurpvca+evLWlKnFhq+/f78blOc9Q7yEuwbkIaJ+bHt38AZjBQNnzRhM3Ooj0jZgEU9MKphQl4gIMCs3sYSFki6xtCBE0ilJ1zd7K193h1kWAswBhOa55XQ82T/AVfGu5qmJVpsNM48afnh5go+AuHBw/WGzixHqsqDKJLbES68lL2ULvvovEZcF9KzsSEXg8sVeYijqtUVm1bAJLLPlroagnynZ2BMPsJ3t0jpLxxkTljJyA6uAO97c+G0qhKkX1DkbJUeg6e5wdY4qmmrJGzf132dMg93zDRwJWyQAK6rR8lbNEooJmoxZFo0xmj/TCICiA=
